window.MAP_DATA = {
  sourceNote:'Mock country-level data for the Europe map. No external API is used. Country geometries are embedded in europe-countries.geojson; indicator values are illustrative decision-support data only.',
  updated:'2026-09-14',
  countries:[
    {id:'ALB',name:'Albania',wei:28,drought:48,rain:-10,irrigated:16},
    {id:'AUT',name:'Austria',wei:8,drought:24,rain:3,irrigated:8},
    {id:'BEL',name:'Belgium',wei:6,drought:21,rain:1,irrigated:7},
    {id:'BGR',name:'Bulgaria',wei:31,drought:55,rain:-13,irrigated:28},
    {id:'BIH',name:'Bosnia and Herzegovina',wei:18,drought:35,rain:-6,irrigated:10},
    {id:'CHE',name:'Switzerland',wei:6,drought:18,rain:5,irrigated:5},
    {id:'CYP',name:'Cyprus',wei:53,drought:82,rain:-32,irrigated:31},
    {id:'CZE',name:'Czechia',wei:13,drought:31,rain:-4,irrigated:9},
    {id:'DEU',name:'Germany',wei:11,drought:27,rain:-2,irrigated:8},
    {id:'DNK',name:'Denmark',wei:10,drought:25,rain:0,irrigated:6},
    {id:'ESP',name:'Spain',wei:38,drought:71,rain:-21,irrigated:49},
    {id:'EST',name:'Estonia',wei:4,drought:15,rain:4,irrigated:3},
    {id:'FIN',name:'Finland',wei:3,drought:12,rain:6,irrigated:2},
    {id:'FRA',name:'France',wei:17,drought:39,rain:-8,irrigated:13},
    {id:'GBR',name:'United Kingdom',wei:9,drought:22,rain:2,irrigated:4},
    {id:'GRC',name:'Greece',wei:27,drought:57,rain:-15,irrigated:27},
    {id:'HRV',name:'Croatia',wei:16,drought:36,rain:-7,irrigated:11},
    {id:'HUN',name:'Hungary',wei:20,drought:46,rain:-11,irrigated:18},
    {id:'IRL',name:'Ireland',wei:5,drought:18,rain:4,irrigated:3},
    {id:'ISL',name:'Iceland',wei:2,drought:8,rain:7,irrigated:1},
    {id:'ITA',name:'Italy',wei:30,drought:60,rain:-16,irrigated:34},
    {id:'LTU',name:'Lithuania',wei:5,drought:17,rain:3,irrigated:3},
    {id:'LUX',name:'Luxembourg',wei:6,drought:19,rain:0,irrigated:4},
    {id:'LVA',name:'Latvia',wei:4,drought:16,rain:4,irrigated:2},
    {id:'MDA',name:'Moldova',wei:24,drought:49,rain:-12,irrigated:21},
    {id:'MKD',name:'North Macedonia',wei:32,drought:58,rain:-15,irrigated:24},
    {id:'MLT',name:'Malta',wei:68,drought:73,rain:-25,irrigated:7},
    {id:'MNE',name:'Montenegro',wei:22,drought:42,rain:-8,irrigated:12},
    {id:'NLD',name:'Netherlands',wei:7,drought:23,rain:1,irrigated:9},
    {id:'NOR',name:'Norway',wei:3,drought:10,rain:7,irrigated:2},
    {id:'POL',name:'Poland',wei:12,drought:29,rain:-4,irrigated:7},
    {id:'PRT',name:'Portugal',wei:30,drought:61,rain:-19,irrigated:20},
    {id:'ROU',name:'Romania',wei:19,drought:45,rain:-10,irrigated:17},
    {id:'SRB',name:'Serbia',wei:25,drought:50,rain:-12,irrigated:19},
    {id:'SVK',name:'Slovakia',wei:11,drought:28,rain:-3,irrigated:7},
    {id:'SVN',name:'Slovenia',wei:9,drought:27,rain:-1,irrigated:6},
    {id:'SWE',name:'Sweden',wei:4,drought:14,rain:5,irrigated:2},
    {id:'TUR',name:'Türkiye',wei:30,drought:59,rain:-17,irrigated:31},
    {id:'UKR',name:'Ukraine',wei:18,drought:41,rain:-9,irrigated:15},
    {id:'BLR',name:'Belarus',wei:6,drought:19,rain:2,irrigated:3},
    {id:'RUS',name:'Russia',wei:7,drought:22,rain:1,irrigated:4}
  ]
};
