const countries=window.MAP_DATA.countries.filter(c=>['ESP','FRA','ITA','GRC','PRT'].includes(c.id));
const regions=window.SOUTH_EUROPE_REGIONS||{};
let active='wei',selectedId='ESP',selectedRegion='';
const $=s=>document.querySelector(s);
const meta={wei:{title:'Water scarcity · WEI+',unit:'%',legend:['<20 lower','20–40 stressed','>40 severe']},drought:{title:'Drought pressure',unit:'/100',legend:['<40 lower','40–60 watch','>60 high']},rain:{title:'Rainfall anomaly',unit:'%',legend:['>-10 near normal','-10 to -20 dry','<-20 very dry']},irrigated:{title:'Irrigation exposure',unit:'%',legend:['<20 lower','20–40 medium','>40 high']}};
const shapes={ESP:'M150 280 L220 250 L300 260 L330 320 L300 380 L220 390 L155 350 Z',FRA:'M105 150 L190 125 L235 170 L220 245 L175 250 L135 220 Z',ITA:'M315 205 L350 220 L345 275 L385 315 L365 350 L335 305 L300 285 L305 235 Z',GRC:'M390 300 L430 305 L450 340 L420 365 L390 350 L375 325 Z',PRT:'M85 255 L110 250 L120 330 L95 345 L78 300 Z'};
function country(id){return countries.find(c=>c.id===id)}
function value(c){return c?.[active]??0}
function severity(c){const v=value(c);if(active==='rain')return v<=-20?2:v<=-10?1:0;if(active==='wei')return v>=40?2:v>=20?1:0;return v>=60?2:v>=40?1:0}
function color(c){return['#79a985','#e0a63b','#c95d46'][severity(c)]}
function decision(c){const s=Math.min(100,c.wei*.9+c.drought*.45+Math.max(0,-c.rain)*.35+c.irrigated*.2);return s>=75?['Protect reserve water','Very high mock pressure: favour lower-demand crops and keep a larger seasonal buffer.']:s>=50?['Rebalance exposed blocks','Protect high-value irrigated hectares and test a more water-efficient crop mix.']:['Maintain with monitoring','Mock pressure is lower; preserve a contingency buffer and review conditions regularly.']}
function regionObj(a){return{id:a[0],name:a[1],wei:a[2],drought:a[3],rain:a[4],irrigated:a[5]}}
function detail(c,r){const x=r||c,d=decision(x),label=severity(x)===2?'High':severity(x)===1?'Watch':'Lower';$('#detail').innerHTML=`<span class="eyebrow">${r?'REGION INDICATOR':'COUNTRY EVIDENCE'}</span><h2>${r?r.name:c.name}</h2><div class="region-country">${r?c.name+' · Southern Europe':'Southern Europe'} · mock snapshot ${window.MAP_DATA.updated}</div><span class="pressure-badge ${label==='High'?'severe':label==='Watch'?'high':'watch'}">${label} pressure</span><div class="detail-grid"><div class="detail-metric"><span>WEI+</span><strong>${x.wei}%</strong><small>mock value</small></div><div class="detail-metric"><span>Drought pressure</span><strong>${x.drought}/100</strong><small>mock value</small></div><div class="detail-metric"><span>Rain anomaly</span><strong>${x.rain}%</strong><small>mock value</small></div><div class="detail-metric"><span>Irrigation exposure</span><strong>${x.irrigated}%</strong><small>mock value</small></div></div><div class="decision-box"><span>AquaCrop implication</span><strong>${d[0]}</strong><p>${d[1]}</p></div>`}
function legend(){const cs=['#79a985','#e0a63b','#c95d46'];$('#legend').innerHTML=meta[active].legend.map((x,i)=>`<span><i style="background:${cs[i]}"></i>${x}</span>`).join('');$('#hero-layer').textContent=meta[active].title}
function renderMap(){const box=$('#map');box.innerHTML=`<svg class="simple-europe" viewBox="0 0 540 410" role="img" aria-label="Europe country map"><rect width="540" height="410" rx="18" fill="#edf5f1"/>${countries.map(c=>`<path class="country-shape ${c.id===selectedId?'selected':''}" data-id="${c.id}" d="${shapes[c.id]}" fill="${color(c)}"><title>${c.name}</title></path>`).join('')}<text x="250" y="95" class="map-label">EUROPE</text><text x="245" y="115" class="map-sub">Southern Europe focus</text></svg>`;document.querySelectorAll('.country-shape').forEach(p=>p.addEventListener('click',()=>selectCountry(p.dataset.id)))}
function populateRegions(id){const sel=$('#region'),items=regions[id]||[];sel.disabled=!items.length;sel.innerHTML=items.length?'<option value="">Whole country</option>'+items.map(a=>`<option value="${a[0]}">${a[1]}</option>`).join(''):'<option value="">No regional indicator</option>';selectedRegion=''}
function selectCountry(id){const c=country(id);if(!c)return;selectedId=id;$('#country').value=id;populateRegions(id);detail(c);renderMap()}
function selectRegion(id){selectedRegion=id;const arr=(regions[selectedId]||[]).find(a=>a[0]===id);detail(country(selectedId),arr?regionObj(arr):null)}
function renderRows(){const sorted=countries.slice().sort((a,b)=>severity(b)-severity(a)||a.name.localeCompare(b.name));$('#rows').innerHTML=sorted.map(c=>`<tr data-id="${c.id}"><td><strong>${c.name}</strong></td><td>${c.wei}%</td><td>${c.drought}/100</td><td>${c.rain}%</td><td>${c.irrigated}%</td><td class="signal">${decision(c)[0]}</td></tr>`).join('');document.querySelectorAll('#rows tr').forEach(tr=>tr.onclick=()=>selectCountry(tr.dataset.id))}
function filters(){$('#country').innerHTML='<option value="">Select a country</option>'+countries.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${c.id}">${c.name}</option>`).join('');populateRegions(selectedId)}
filters();legend();renderRows();detail(country(selectedId));renderMap();$('#source-note').textContent=window.MAP_DATA.sourceNote+' Country/region selector restricted to Spain, France, Italy, Greece and Portugal.';$('#layer').onchange=e=>{active=e.target.value;legend();renderMap();renderRows();detail(country(selectedId))};$('#country').onchange=e=>e.target.value&&selectCountry(e.target.value);$('#region').onchange=e=>selectRegion(e.target.value);