const regions=window.MAP_DATA.regions;let active='wei',map,markers=[];const $=s=>document.querySelector(s);const meta={wei:{title:'Water scarcity · WEI+',unit:'%',legend:['<20 lower','20–40 stressed','>40 severe']},drought:{title:'Drought pressure',unit:'/100',legend:['<40 lower','40–60 watch','>60 high']},rain:{title:'Rainfall anomaly',unit:'%',legend:['>-10 near normal','-10 to -20 dry','<-20 very dry']},irrigated:{title:'Irrigation exposure',unit:'%',legend:['<20 lower','20–40 medium','>40 high']}};
function value(r){return r[active]}function severity(r){const v=value(r);if(active==='rain')return v<=-20?2:v<=-10?1:0;if(active==='wei')return v>=40?2:v>=20?1:0;return v>=60?2:v>=40?1:0}function color(r){return ['#67aa76','#e0a63b','#c95d46'][severity(r)]}function decision(r){const score=Math.round(Math.min(100,r.wei*.9+r.drought*.45+Math.max(0,-r.rain)*.35+r.irrigated*.2));if(score>=75)return['Protect reserve water','Very high combined pressure: favour lower-demand crops and keep a larger seasonal buffer.'];if(score>=50)return['Rebalance exposed blocks','Protect high-value irrigated hectares and test a more water-efficient crop mix.'];return['Maintain with monitoring','Current combined pressure is lower; preserve a contingency buffer and review conditions regularly.']}
function detail(r){if(!r)return;const d=decision(r);$('#detail').innerHTML=`<span class="eyebrow">${r.id} · EUROPEAN REGIONAL EVIDENCE</span><h2>${r.name}</h2><div class="region-country">${r.country} · reference snapshot ${window.MAP_DATA.updated}</div><span class="pressure-badge ${r.status.toLowerCase()}">${r.status} pressure</span><div class="detail-grid"><div class="detail-metric"><span>WEI+</span><strong>${r.wei}%</strong><small>${r.weiSeason}</small></div><div class="detail-metric"><span>Drought pressure</span><strong>${r.drought}/100</strong><small>EDO-aligned snapshot</small></div><div class="detail-metric"><span>Rain anomaly</span><strong>${r.rain}%</strong><small>vs reference climate</small></div><div class="detail-metric"><span>Irrigation exposure</span><strong>${r.irrigated}%</strong><small>agricultural context</small></div></div><div class="decision-box"><span>AquaCrop implication</span><strong>${d[0]}</strong><p>${d[1]}</p></div>`}
function legend(){const cs=['#67aa76','#e0a63b','#c95d46'];$('#legend').innerHTML=meta[active].legend.map((x,i)=>`<span><i style="background:${cs[i]}"></i>${x}</span>`).join('');$('#hero-layer').textContent=meta[active].title}
function popup(r){return `<strong>${r.name}</strong><br>${meta[active].title}: <b>${value(r)}${meta[active].unit}</b><br><small>Click for decision context</small>`}
function renderMarkers(){if(!map)return;markers.forEach(m=>m.remove());markers=[];const country=$('#country').value;regions.filter(r=>country==='all'||r.country===country).forEach(r=>{const m=L.circleMarker([r.lat,r.lon],{radius:7+severity(r)*3,color:'#fff',weight:2,fillColor:color(r),fillOpacity:.9}).addTo(map).bindPopup(popup(r));m.on('click',()=>{detail(r);$('#region').value=r.id});markers.push(m)})}
function renderRows(){const country=$('#country').value;$('#rows').innerHTML=regions.filter(r=>country==='all'||r.country===country).sort((a,b)=>severity(b)-severity(a)||b.wei-a.wei).map(r=>`<tr data-id="${r.id}"><td><strong>${r.name}</strong><br><small>${r.country}</small></td><td>${r.wei}%</td><td>${r.drought}/100</td><td>${r.rain}%</td><td>${r.irrigated}%</td><td class="signal">${decision(r)[0]}</td></tr>`).join('');document.querySelectorAll('#rows tr').forEach(tr=>tr.onclick=()=>focus(tr.dataset.id))}
function focus(id){const r=regions.find(x=>x.id===id);if(!r)return;detail(r);if(map){map.flyTo([r.lat,r.lon],6,{duration:.7});const m=markers.find(x=>{const p=x.getLatLng();return Math.abs(p.lat-r.lat)<.01&&Math.abs(p.lng-r.lon)<.01});if(m)m.openPopup()}}
function filters(){const countries=[...new Set(regions.map(r=>r.country))].sort();$('#country').innerHTML='<option value="all">All Europe</option>'+countries.map(c=>`<option>${c}</option>`).join('');$('#region').innerHTML='<option value="">Select a European region</option>'+regions.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(r=>`<option value="${r.id}">${r.name} · ${r.country}</option>`).join('')}
function initMap(){if(!window.L){$('#fallback').style.display='block';return}map=L.map('map',{scrollWheelZoom:true,maxBounds:[[33,-12],[72,42]],maxBoundsViscosity:.8}).setView([47.2,10.0],4.2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:10,attribution:'© OpenStreetMap contributors'}).addTo(map);renderMarkers()}
filters();legend();renderRows();$('#source-note').textContent=window.MAP_DATA.sourceNote;initMap();$('#layer').onchange=e=>{active=e.target.value;legend();renderMarkers();renderRows()};$('#country').onchange=()=>{renderMarkers();renderRows()};$('#region').onchange=e=>focus(e.target.value);detail(regions.find(r=>r.id==='ES62'));