const countries=window.MAP_DATA.countries;let active='wei',map,countryLayer,selectedId='ESP';const $=s=>document.querySelector(s);const meta={wei:{title:'Water scarcity · WEI+',unit:'%',legend:['<20 lower','20–40 stressed','>40 severe']},drought:{title:'Drought pressure',unit:'/100',legend:['<40 lower','40–60 watch','>60 high']},rain:{title:'Rainfall anomaly',unit:'%',legend:['>-10 near normal','-10 to -20 dry','<-20 very dry']},irrigated:{title:'Irrigation exposure',unit:'%',legend:['<20 lower','20–40 medium','>40 high']}};
function value(c){return c?.[active]??0}function severity(c){const v=value(c);if(active==='rain')return v<=-20?2:v<=-10?1:0;if(active==='wei')return v>=40?2:v>=20?1:0;return v>=60?2:v>=40?1:0}function color(c){return['#79a985','#e0a63b','#c95d46'][severity(c)]}function country(id){return countries.find(c=>c.id===id)}function decision(c){const s=Math.round(Math.min(100,c.wei*.9+c.drought*.45+Math.max(0,-c.rain)*.35+c.irrigated*.2));return s>=75?['Protect reserve water','Very high mock pressure: favour lower-demand crops and keep a larger seasonal buffer.']:s>=50?['Rebalance exposed blocks','Protect high-value irrigated hectares and test a more water-efficient crop mix.']:['Maintain with monitoring','Mock pressure is lower; preserve a contingency buffer and review conditions regularly.']}
function detail(c){if(!c)return;const d=decision(c),label=severity(c)===2?'High':severity(c)===1?'Watch':'Lower';$('#detail').innerHTML=`<span class="eyebrow">${c.id} · COUNTRY EVIDENCE</span><h2>${c.name}</h2><div class="region-country">Europe · mock snapshot ${window.MAP_DATA.updated}</div><span class="pressure-badge ${label==='High'?'severe':label==='Watch'?'high':'watch'}">${label} pressure</span><div class="detail-grid"><div class="detail-metric"><span>WEI+</span><strong>${c.wei}%</strong><small>mock value</small></div><div class="detail-metric"><span>Drought pressure</span><strong>${c.drought}/100</strong><small>mock value</small></div><div class="detail-metric"><span>Rain anomaly</span><strong>${c.rain}%</strong><small>mock value</small></div><div class="detail-metric"><span>Irrigation exposure</span><strong>${c.irrigated}%</strong><small>mock value</small></div></div><div class="decision-box"><span>AquaCrop implication</span><strong>${d[0]}</strong><p>${d[1]}</p></div>`}
function legend(){const cs=['#79a985','#e0a63b','#c95d46'];$('#legend').innerHTML=meta[active].legend.map((x,i)=>`<span><i style="background:${cs[i]}"></i>${x}</span>`).join('');$('#hero-layer').textContent=meta[active].title}
function style(feature){const c=country(feature.properties.id),selected=feature.properties.id===selectedId;return{color:selected?'#0d5853':'#ffffff',weight:selected?3:1.2,fillColor:c?color(c):'#dce5e1',fillOpacity:selected?0.95:0.78}}
function selectCountry(id,fit=false){if(!country(id))return;selectedId=id;$('#country').value=id;detail(country(id));if(countryLayer){countryLayer.setStyle(style);countryLayer.eachLayer(l=>{if(l.feature.properties.id===id){l.bringToFront();if(fit)map.fitBounds(l.getBounds(),{padding:[28,28],maxZoom:5})}})}}
function renderRows(){const sorted=countries.slice().sort((a,b)=>severity(b)-severity(a)||a.name.localeCompare(b.name));$('#rows').innerHTML=sorted.map(c=>`<tr data-id="${c.id}"><td><strong>${c.name}</strong></td><td>${c.wei}%</td><td>${c.drought}/100</td><td>${c.rain}%</td><td>${c.irrigated}%</td><td class="signal">${decision(c)[0]}</td></tr>`).join('');document.querySelectorAll('#rows tr').forEach(tr=>tr.onclick=()=>selectCountry(tr.dataset.id,true))}
function filters(){const visible=countries.slice().sort((a,b)=>a.name.localeCompare(b.name));$('#country').innerHTML='<option value="">Select a country</option>'+visible.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}
async function initMap(){try{const geo=await window.loadEuropeGeoJSON();map=L.map('map',{zoomControl:true,attributionControl:false,minZoom:3,maxZoom:6,scrollWheelZoom:false,worldCopyJump:false,maxBounds:[[33,-26],[72,45]],maxBoundsViscosity:1});countryLayer=L.geoJSON(geo,{filter:f=>country(f.properties.id),style,onEachFeature:(f,l)=>{l.on({click:()=>selectCountry(f.properties.id,false),mouseover:e=>{if(f.properties.id!==selectedId)e.target.setStyle({weight:2,color:'#7ca59d'})},mouseout:()=>countryLayer.setStyle(style)});l.bindTooltip(f.properties.name,{sticky:true,direction:'top'})}}).addTo(map);map.fitBounds(countryLayer.getBounds(),{padding:[12,12]});setTimeout(()=>map.invalidateSize(),0);selectCountry(selectedId,false);$('#map-status').textContent='Europe country map loaded';}catch(err){console.error(err);$('#fallback').style.display='block';$('#map-status').textContent='Map could not load';}}
filters();legend();renderRows();$('#source-note').textContent=window.MAP_DATA.sourceNote;$('#layer').onchange=e=>{active=e.target.value;legend();if(countryLayer)countryLayer.setStyle(style);renderRows();detail(country(selectedId))};$('#country').onchange=e=>e.target.value&&selectCountry(e.target.value,true);detail(country(selectedId));initMap();
