const D=window.PROVINCE_MAP_DATA,G=window.EUROPE_GEO_DATA,$=s=>document.querySelector(s);let active='wei',selected=null,history=[],planningRegion='all';
const meta={wei:{title:'Water scarcity · WEI+',labels:['Lower','Stressed','Severe'],cuts:[20,40]},drought:{title:'Drought pressure',labels:['Lower','Watch','High'],cuts:[40,60]},rain:{title:'Rainfall anomaly',labels:['Near normal','Dry','Very dry'],cuts:[-10,-20],reverse:true},irrigated:{title:'Irrigation exposure',labels:['Lower','Medium','High'],cuts:[20,40]}};
const regionDefs={iberia:{name:'Iberia',description:'Spain and Portugal',countries:['ESP','PRT'],color:'#6fa99d'},'southern-france':{name:'Southern France',description:'Mediterranean France',countries:['FRA'],color:'#7c9db8'},'italy-islands':{name:'Italy & Islands',description:'Italy, Malta and Sardinia/Sicily',countries:['ITA','MLT'],color:'#b593c5'},'balkans-greece':{name:'Balkans & Greece',description:'Albania and Greece',countries:['ALB','GRC'],color:'#d1a25e'}};
const isoToRegion={ESP:'iberia',PRT:'iberia',FRA:'southern-france',ITA:'italy-islands',MLT:'italy-islands',ALB:'balkans-greece',GRC:'balkans-greece'},colorFor=n=>['#9bc3aa','#e8be62','#cc6b53'][n],obj=(a,c)=>({id:a[0],name:a[1],country:c,wei:a[2],drought:a[3],rain:a[4],irrigated:a[5]}),all=()=>D.countries.flatMap(c=>(D.provinces[c.id]||[]).map(a=>obj(a,c))),find=id=>all().find(p=>p.id===id);
const severity=p=>{const v=p[active],m=meta[active];return m.reverse?(v<=m.cuts[1]?2:v<=m.cuts[0]?1:0):(v>=m.cuts[1]?2:v>=m.cuts[0]?1:0)};
const countryScore=iso=>{const ps=all().filter(p=>p.country.id===iso);if(!ps.length)return-1;const v=ps.reduce((s,p)=>s+p[active],0)/ps.length,m=meta[active];return m.reverse?(v<=m.cuts[1]?2:v<=m.cuts[0]?1:0):(v>=m.cuts[1]?2:v>=m.cuts[0]?1:0)};
function populateCountries(){const a=planningRegion==='all'?D.countries:D.countries.filter(c=>regionDefs[planningRegion].countries.includes(c.id));$('#country').innerHTML=a.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');if(a[0])populateProvinces(a[0].id)}function populateProvinces(iso){$('#province').innerHTML=(D.provinces[iso]||[]).map(a=>`<option value="${a[0]}">${a[1]}</option>`).join('')}
function advice(p){const s=p.wei*.8+p.drought*.45+Math.max(0,-p.rain)*.35+p.irrigated*.2;return s>75?['Protect water first','Reduce high-water crop exposure, protect a larger reserve and prioritise irrigation on the highest-value blocks.']:s>52?['Rebalance the crop plan','Keep drought-tolerant crops as the anchor, tighten irrigation scheduling and preserve a contingency buffer.']:['Maintain with monitoring','Current mock pressure is manageable. Keep a reserve, monitor rainfall and review the plan before peak summer demand.']}
function renderDetail(){if(!selected){$('#detail').innerHTML='<span class="eyebrow">EUROPE CONTEXT</span><h2>Regional decision map</h2><p>Select a planning region or country. Real geography is shown for context, while water-pressure indicators are prototype values.</p><div class="decision-box"><span>Planning lens</span><strong>Southern Europe water pressure</strong><p>Four macro-regions help cooperatives compare climate and irrigation exposure at a decision-friendly level.</p></div>';return}const r=regionDefs[isoToRegion[selected.country.id]],a=advice(selected),s=severity(selected);$('#detail').innerHTML=`<span class="eyebrow">${r?.name||selected.country.name} · ${selected.country.name}</span><h2>${selected.name}</h2><div class="region-country">Prototype decision evidence · mock indicators</div><span class="pressure-badge ${s===2?'severe':s===1?'high':'watch'}">${meta[active].labels[s]}</span><div class="detail-grid"><div class="detail-metric"><span>WEI+</span><strong>${selected.wei}%</strong></div><div class="detail-metric"><span>Drought</span><strong>${selected.drought}/100</strong></div><div class="detail-metric"><span>Rain anomaly</span><strong>${selected.rain}%</strong></div><div class="detail-metric"><span>Irrigation exposure</span><strong>${selected.irrigated}%</strong></div></div><div class="decision-box"><span>Decision implication</span><strong>${a[0]}</strong><p>${a[1]}</p></div>`}
function renderHistory(){$('#history').innerHTML=history.length?history.map(p=>`<button class="history-card" data-id="${p.id}"><span>${regionDefs[isoToRegion[p.country.id]]?.name||p.country.name}</span><strong>${p.name}</strong><small>WEI+ ${p.wei}% · Drought ${p.drought}/100 · Rain ${p.rain}%</small></button>`).join(''):'<div class="history-empty">Select Southern European regions to build a comparison log.</div>';document.querySelectorAll('.history-card').forEach(b=>b.onclick=()=>select(b.dataset.id,false))}
function renderStrip(){$('#region-strip').innerHTML=Object.entries(regionDefs).map(([id,r])=>`<button class="region-chip${planningRegion===id?' active':''}" data-region="${id}"><span class="region-dot" style="background:${r.color}"></span><strong>${r.name}</strong><span>${r.description} · ${r.countries.length} countries</span></button>`).join('');document.querySelectorAll('.region-chip').forEach(b=>b.onclick=()=>setPlanningRegion(b.dataset.region))}
function select(id,add=true){const p=find(id);if(!p)return;selected=p;planningRegion=isoToRegion[p.country.id]||'all';$('#planning-region').value=planningRegion;populateCountries();$('#country').value=p.country.id;populateProvinces(p.country.id);$('#province').value=p.id;if(add)history=[p,...history.filter(x=>x.id!==p.id)].slice(0,6);renderDetail();renderHistory();renderMap();renderStrip()}
function setPlanningRegion(id){planningRegion=id;selected=null;$('#planning-region').value=id;populateCountries();renderDetail();renderMap();renderStrip()}
function renderMap(){const allowed=planningRegion==='all'?null:new Set(regionDefs[planningRegion].countries);const countries=G.countries.map(c=>{const score=countryScore(c.id),dim=allowed&&!allowed.has(c.id);return`<g class="country-group${dim?' region-dim':''}" data-iso="${c.id}">${c.paths.map(d=>`<path class="country-shape${selected?.country.id===c.id?' selected':''}" d="${d}" fill="${score<0?'#e9efec':colorFor(score)}" fill-rule="evenodd"><title>${c.name}</title></path>`).join('')}</g>`}).join('');const regions=Object.values(G.regions).map(r=>{const p=find(r.id),dim=allowed&&!allowed.has(p?.country.id);return`<g class="region-shape${dim?' region-dim':''}" data-region-id="${r.id}">${r.paths.map(d=>`<path d="${d}" fill="${p?colorFor(severity(p)):'#d9e8e3'}" fill-opacity=".78" fill-rule="evenodd"><title>${p?.name||r.id}</title></path>`).join('')}</g>`}).join('');$('#map').innerHTML=`<svg class="province-europe real-europe" viewBox="0 0 ${G.width} ${G.height}" role="img" aria-label="Real geographic map of Europe"><rect width="${G.width}" height="${G.height}" rx="18" fill="#f7faf8"/><text x="34" y="40" class="map-title">EUROPE</text><text x="34" y="62" class="map-subtitle">Real country and regional geography · prototype indicators</text><g class="country-layer">${countries}</g><g class="region-layer">${regions}</g></svg>`;document.querySelectorAll('[data-region-id]').forEach(el=>el.onclick=()=>select(el.dataset.regionId));document.querySelectorAll('.country-group').forEach(el=>el.onclick=()=>{const p=all().find(x=>x.country.id===el.dataset.iso);if(p)select(p.id)});$('#hero-layer').textContent=planningRegion==='all'?meta[active].title:regionDefs[planningRegion].name+' · '+meta[active].title;$('#legend').innerHTML=['#9bc3aa','#e8be62','#cc6b53'].map((c,i)=>`<span><i style="background:${c}"></i>${meta[active].labels[i]}</span>`).join('')+'<span><i style="background:#e9efec"></i>Context only</span>'}
populateCountries();renderDetail();renderHistory();renderStrip();renderMap();$('#layer').onchange=e=>{active=e.target.value;renderDetail();renderMap()};$('#planning-region').onchange=e=>setPlanningRegion(e.target.value);$('#country').onchange=e=>{populateProvinces(e.target.value);const a=D.provinces[e.target.value]?.[0];if(a)select(a[0])};$('#province').onchange=e=>select(e.target.value);
